# Generated by Django 2.2 on 2021-06-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=45)),
                ('prep_time', models.CharField(max_length=20)),
                ('procedure', models.CharField(max_length=455, null=True)),
                ('ingredients', models.TextField(max_length=455, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='swap_app.User')),
                ('favorite', models.ManyToManyField(related_name='fav_recipes', to='swap_app.User')),
            ],
        ),
    ]
