# Generated by Django 2.2 on 2021-06-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0003_auto_20210620_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=455, null=True),
        ),
    ]
