# Generated by Django 2.2 on 2021-06-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0004_auto_20210620_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='swap_app.User'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.CharField(max_length=455, null=True),
        ),
    ]
