# Generated by Django 2.2 on 2021-06-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0005_auto_20210620_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=45)),
                ('prep_time', models.CharField(max_length=20)),
                ('procedure', models.CharField(max_length=455)),
                ('ingredients', models.TextField(max_length=455)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help', to='swap_app.User')),
            ],
        ),
    ]
