# Generated by Django 2.2 on 2021-06-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0006_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='link',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='swap_app.Recipe'),
            preserve_default=False,
        ),
    ]
