# Generated by Django 2.2 on 2021-06-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(max_length=455, null=True),
        ),
    ]
