# Generated by Django 2.2 on 2021-07-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0010_auto_20210708_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='knife.jpg', upload_to='images'),
        ),
    ]
