# Generated by Django 2.2 on 2021-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0011_auto_20210708_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='images'),
        ),
    ]
