# Generated by Django 2.2 on 2021-07-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0012_auto_20210709_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
