# Generated by Django 2.2 on 2021-07-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0014_auto_20210712_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=255)),
                ('prep_time', models.CharField(max_length=20)),
                ('procedure', models.CharField(max_length=455, null=True)),
                ('ingredients', models.TextField(max_length=455, null=True)),
                ('notes', models.TextField(max_length=455, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='test_cat_recipes', to='swap_app.Category')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_recipes', to='swap_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('for_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_images', to='swap_app.TestRec')),
            ],
        ),
    ]
