# Generated by Django 2.2 on 2021-07-23 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0015_testimg_testrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='knife_roll_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kn_ro_pics', to='swap_app.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_pics', to='swap_app.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='wall_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall_pics', to='swap_app.User'),
        ),
        migrations.DeleteModel(
            name='TestImg',
        ),
    ]
