# Generated by Django 2.2 on 2021-07-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0017_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='swap_app.User'),
        ),
    ]
