# Generated by Django 2.2 on 2021-07-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0019_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='swap_app.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='gr_admin',
            field=models.ManyToManyField(related_name='amdin_members', to='swap_app.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='group_members', to='swap_app.User'),
        ),
    ]
