# Generated by Django 3.2.5 on 2021-07-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0025_recipe_group_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='group_rec',
        ),
        migrations.AddField(
            model_name='group',
            name='group_rec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='swap_app.recipe'),
        ),
    ]
