# Generated by Django 3.2.5 on 2021-07-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0026_auto_20210730_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_rec',
        ),
        migrations.AddField(
            model_name='recipe',
            name='group_rec',
            field=models.ManyToManyField(related_name='group_recs', to='swap_app.Group'),
        ),
    ]
