# Generated by Django 3.2.5 on 2021-07-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0027_auto_20210730_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='group_rec',
        ),
        migrations.AddField(
            model_name='recipe',
            name='group_rec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_recs', to='swap_app.group'),
        ),
    ]
