# Generated by Django 3.2.5 on 2022-06-18 17:22

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('swap_app', '0029_alter_invite_for_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rec_name',
            field=models.CharField(max_length=255, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
